// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiZdriAQ55hRN5gXA_Ch7LptlOfkpg1DU',
    appId: '1:180158879751:web:c59aa27f51c11ecbd732a2',
    messagingSenderId: '180158879751',
    projectId: 'flutter-abc12',
    authDomain: 'flutter-abc12.firebaseapp.com',
    storageBucket: 'flutter-abc12.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZPVvxQbUcHd4Kj3SN9TD60I-E3rrcoDc',
    appId: '1:180158879751:android:bcd1dda638822dc2d732a2',
    messagingSenderId: '180158879751',
    projectId: 'flutter-abc12',
    storageBucket: 'flutter-abc12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe84bKu1VOmn_PQnTLMW39Eytwb_7g7SU',
    appId: '1:180158879751:ios:efafb13090bbcaebd732a2',
    messagingSenderId: '180158879751',
    projectId: 'flutter-abc12',
    storageBucket: 'flutter-abc12.appspot.com',
    iosClientId: '180158879751-50bcmd5a07jbtrdrecmovstro2m9tjfk.apps.googleusercontent.com',
    iosBundleId: 'ifgab1.projectGet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe84bKu1VOmn_PQnTLMW39Eytwb_7g7SU',
    appId: '1:180158879751:ios:bd501468701b214ad732a2',
    messagingSenderId: '180158879751',
    projectId: 'flutter-abc12',
    storageBucket: 'flutter-abc12.appspot.com',
    iosClientId: '180158879751-4qa3vrqv09stj0uv1uafhsf075mf5c38.apps.googleusercontent.com',
    iosBundleId: 'ifgab1.projectGet.RunnerTests',
  );
}
